Update go version to 1.21
code-ready/machine-driver-libvirt pull request #118
Opened 2024-05-27 06:28 UTC by praveenkumar

2024-05-27 14:16 UTC, cfergeau requested changes
Why?

2024-06-13 08:31 UTC, praveenkumar commented
> Why?

@cfergeau added in the commit logs

2024-06-19 04:41 UTC, anjannath approved these changes

2024-06-19 08:30 UTC, cfergeau reviewed
I'm still not 100% sure from the commit log if this is a change which is required, or if it's something we do for consistency with the rest of our stack.
The fact that go.mod says `1.19` does not prevent us from using 1.21 or 1.22 for building.

2024-06-19 09:11 UTC, praveenkumar commented
> I'm still not 100% sure from the commit log if this is a change which is required, or if it's something we do for consistency with the rest of our stack. 

> The fact that go.mod says `1.19` does not prevent us from using 1.21 or 1.22 for building.

it doesn't prevent us to use latest version of golang but it also doesn't prevent some to build it on older version since it is already EOL so I am not sure what else would be best reason to have it in.

2024-06-19 10:03 UTC, cfergeau commented
> I'm still not 100% sure from the commit log if this is a change which is required, or if it's something we do for consistency with the rest of our stack.

I still have no idea about this. I think you are saying this is not a required change (required because something is broken if we try to build with go 1.19 or 1.20), but that it's  better to have this for consistency/because go older than 1.21 is not supported/..., which is fine with me.

2024-06-19 11:06 UTC, praveenkumar commented
> > I'm still not 100% sure from the commit log if this is a change which is required, or if it's something we do for consistency with the rest of our stack.
> 
> I still have no idea about this. I think you are saying this is not a required change (required because something is broken if we try to build with go 1.19 or 1.20), but that it's better to have this for consistency/because go older than 1.21 is not supported/..., which is fine with me.

That's what I put in the commit log, since 1.18 is outdated and our tooling already moved to 1.21

2024-06-19 12:10 UTC, cfergeau approved these changes

2024-06-20 04:10 UTC, merged