README: Update as per rename & repo location
code-ready/machine-driver-libvirt pull request #31
Opened 2019-09-10 14:51 UTC by zeenix

2019-09-10 15:25 UTC, cfergeau requested changes
I'm afraid you put your hands in a can of worms, you can delete quite a bit of the README file :)

2019-09-10 15:25 UTC, cfergeau commented on README.md
> +# docker-machine-libvirt
:+1:

2019-09-10 15:25 UTC, cfergeau commented on README.md
> +  page and download the docker-machine-driver-libvirt binary, putting it
Hmm the whole README is going to be confusing as we don't expect users to download it separately, to run it standalone, and some parts it refers to (boot2iso) are probably not even working at all. Probably better to replace most of the file with some short text saying this is a driver used by CodeReady Containers in order to create/run VMs on linux using libvirt.

2019-09-11 11:29 UTC, zeenix commented
@cfergeau Thanks for the quick review. PTALA. :)

2019-09-11 15:32 UTC, cfergeau approved these changes

2019-09-11 15:32 UTC, merged